name: Linux Latest RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y unzip xrdp xfce4 xfce4-goodies dbus-x11 x11-xserver-utils jq

    - name: Download Ngrok
      run: |
        curl -L https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
        unzip ngrok.zip
        rm ngrok.zip

    - name: Download start.sh and loop.sh
      run: |
        curl -L https://raw.githubusercontent.com/HenCodersDeveloper/TestLinux/refs/heads/main/start.sh -o start.sh
        curl -L https://raw.githubusercontent.com/HenCodersDeveloper/TestLinux/refs/heads/main/loop.sh -o loop.sh
        chmod +x start.sh loop.sh

    - name: Start RDP Session
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: ./start.sh

    - name: Keep Process Running
      run: ./loop.sh
