name: Linux Latest RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok
      run: |
        curl -L https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -o ngrok.tgz
        tar -xvzf ngrok.tgz
        chmod +x ngrok
        rm ngrok.tgz

    - name: Download start.sh and loop.sh
      run: |
        curl -L https://raw.githubusercontent.com/HenCodersDeveloper/TestLinux/refs/heads/main/start.sh -o start.sh
        curl -L https://raw.githubusercontent.com/HenCodersDeveloper/TestLinux/refs/heads/main/loop.sh -o loop.sh
        chmod +x start.sh loop.sh

    - name: Install dependencies for RDP
      run: |
        sudo apt update
        sudo apt install -y xrdp
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Connect to Ngrok
      run: |
        ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        nohup ./ngrok tcp 3389 &> ngrok.log &
        sleep 10
        curl -s http://127.0.0.1:4040/api/tunnels | grep -Eo 'tcp://[0-9a-z\.:]+' || echo "Ngrok tunnel information unavailable."

    - name: Start RDP session
      run: ./start.sh

    - name: Keep the process running
      run: ./loop.sh
